implemented spring security in project
ynik404/online-book-store pull request #15
Opened 2024-07-16 17:52 UTC by ynik404

2024-07-17 10:26 UTC, MentorMateAcademy requested changes

2024-07-17 10:26 UTC, MentorMateAcademy commented on src/main/java/mate/academy/model/Role.java
> +    private static final String ROLE_PREFIX = "ROLE_";
why do you need this prefix?

2024-07-17 11:30 UTC, Elena-Bruyako requested changes
see comments

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +@RequestMapping("/api/books")
```suggestion
@RequestMapping("/books")
```

Add `server.servlet.context-path=/api` to application.properties

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/user/UserRegistrationRequestDto.java
> +    private String username;
Why do you need to change it?

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/user/UserResponseDto.java
> +    private String username;
same

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Role.java
> +
```suggestion
```

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    public void changeBookDescription(@PathVariable Long id, String description) {
It's better to create update method, to update not only description

2024-07-17 11:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +        return userRepository.findByUsername(email)
```suggestion
        return userRepository.findByEmail(email)
```

2024-07-17 12:22 UTC, Elena-Bruyako requested changes
See comment

2024-07-17 12:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    public void updateBookById(@PathVariable Long id, CreateBookRequestDto requestDto) {
```suggestion
    public BookDto updateBook(@PathVariable Long id, CreateBookRequestDto requestDto) {
```

2024-07-18 18:19 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-18 18:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +                        -> new UsernameNotFoundException("Can't find user by email: "
```suggestion
                        -> new EntityNotFoundException("Can't find user by email: "
```

2024-07-18 18:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        Book updatedBook = bookMapper.toModel(requestDto);
```suggestion
        bookMapper.updateBookFromDto(bookDto, book);
```

2024-07-18 18:19 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        book.setTitle(updatedBook.getTitle());
use mapstruct for this logic

2024-07-19 07:10 UTC, Elena-Bruyako requested changes
see pr

2024-07-19 07:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2024-07-19 07:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
>          return userMapper.toUserResponse(savedUser);
```suggestion
        return userMapper.toUserResponse(user);
```

2024-07-19 07:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Role.java
> +@Entity
add get and set

2024-07-20 11:41 UTC, Elena-Bruyako approved these changes
well done

2024-07-20 11:42 UTC, merged