Added Category model
ynik404/online-book-store pull request #17
Opened 2024-08-01 19:58 UTC by ynik404

2024-08-04 15:50 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 15:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/book/BookDto.java
> +    @NotNull
NotBlank for String

2024-08-04 15:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Category.java
> +    private Boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-08-04 15:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid BookDto bookDto) {
Why did you change it? 
You should return BookDto with Id and provide request Dto without

2024-08-04 15:50 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(2000)
why did you decide to change it?

2024-08-04 15:50 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(500)
why did you decide to change it?

2024-08-06 12:51 UTC, okuzan approved these changes

2024-08-06 12:51 UTC, okuzan commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +            referencedColumnNames: id
please always add a new empty line at the end when you this red symbol
![image](https://github.com/user-attachments/assets/29e96a00-d498-4797-8eac-0a23c584ad2e)

2024-08-06 12:51 UTC, okuzan commented on src/main/java/mate/academy/service/impl/CategoryServiceImpl.java
> +
```suggestion
```

2024-09-15 14:13 UTC, merged