Spring boot web solution
ynik404/online-book-store pull request #2
Opened 2024-05-18 06:27 UTC by ynik404

2024-05-18 06:53 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-05-18 06:53 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-05-18 06:53 UTC, Elena-Bruyako commented on src/main/java/mate/academy/mapper/BookMapperImpl.java
> +    public BookDto toDto(Book book) {
Please, use MapStruct to avoid implementing such logic by yourselves

2024-05-18 06:53 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +@Entity
```suggestion
@Entity
@Table(name = "books")
```

Don't use `@Data` for entities, find and read articles about it

2024-05-18 06:53 UTC, Elena-Bruyako commented on pom.xml
> +                            <version>1.18.26</version>
```suggestion
                            <version>${lombok.version}</version>
```

2024-05-18 11:40 UTC, okuzan requested changes

2024-05-18 11:40 UTC, okuzan commented on src/main/java/mate/academy/model/Book.java
> +@Table(name = "books")
You can still use @Getter @Setter, just not @Data, mainly because of equalsAndHashcode part of it

2024-05-19 05:43 UTC, Elena-Bruyako requested changes
Good job. Let's fix some comments

2024-05-19 05:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +    @Override
Please, remove equals and hashCode method, for now you don't need them

2024-05-19 05:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Cannot add book: " + book, e);
```suggestion
            throw new DataProcessingException("Cannot add book: " + book, e);
```

2024-05-19 13:22 UTC, okuzan approved these changes

2024-05-22 11:19 UTC, merged